In [2]:
import numpy as np
from scipy.linalg import lu, qr

# Лабораторная работа №2. Вариант 1

# 1. Создать квадратную матрицу из случайных целых чисел из [-3,3] размера 10. Найти и вычислить минор 4 порядка, расположенный на пересечении 2, 3, 4, 5 строк и 7, 8, 9, 10 столбцов. Использовать срезы матрицы.

In [3]:
matrix = np.random.randint(-3, 4, (10, 10))
print (matrix)
minor = np.linalg.det(matrix[1:5, 6:10])
print(f"Минор 4 порядка: {minor}\n")

[[-3 -3  0  3  3  0 -3 -3  3 -3]
 [ 0 -3 -1  1  3 -1  1  2 -3  3]
 [ 0 -2  0  3  2 -3 -1 -3  1  0]
 [-3  1 -2 -3  2  3 -2 -1  1 -3]
 [ 3  1  1 -3 -1  1 -2  1  1  3]
 [-1 -3  3  3  0  0  2  2  1  0]
 [-2  2 -2  3 -1  2 -3  3 -3 -2]
 [ 1 -3  3 -1  2 -1  2  2  3 -2]
 [ 3 -2 -1 -3  2  3 -1  3  3  0]
 [ 3  0 -3  2  3 -1  0 -1 -1  3]]
Минор 4 порядка: 83.99999999999999



# 2. Создать две матрицы из случайных вещественных чисел из интервала (2,3) подходящего размера. Найти их произведение тремя способами.

In [4]:
matrix1 = np.random.uniform(2, 3, (5, 5))
matrix2 = np.random.uniform(2, 3, (5, 5))

Способ 1: Векторный алгоритм умножения матриц

In [5]:
result_vector = np.zeros((5, 5))
for i in range(5):
    for j in range(5):
        result_vector[i, j] = sum(matrix1[i, k] * matrix2[k, j] for k in range(5))

print(f"Произведение (векторный способ):\n{result_vector}\n")        

Произведение (векторный способ):
[[36.7187245  34.92828924 35.64928468 36.37393262 34.49875703]
 [30.32166635 28.90483454 29.59229999 29.74794314 28.51044839]
 [31.79940734 30.10554386 30.8098793  31.43329315 29.76636904]
 [35.38539955 33.92391113 34.34791164 35.26708785 33.26228711]
 [34.6221584  33.11573344 33.63151116 34.43319274 32.78632386]]



Способ 2: Матричный алгоритм, заполняя матрицу по столбцам

In [6]:
result_matrix = np.zeros((5, 5))
for j in range(5):
    result_matrix[:, j] = matrix1 @ matrix2[:, j]

print(f"Произведение (матричный способ):\n{result_matrix}\n")

Произведение (матричный способ):
[[36.7187245  34.92828924 35.64928468 36.37393262 34.49875703]
 [30.32166635 28.90483454 29.59229999 29.74794314 28.51044839]
 [31.79940734 30.10554386 30.8098793  31.43329315 29.76636904]
 [35.38539955 33.92391113 34.34791164 35.26708785 33.26228711]
 [34.6221584  33.11573344 33.63151116 34.43319274 32.78632386]]



Способ 3: Проверка с помощью np.dot

In [7]:
result_dot = np.dot(matrix1, matrix2)

print(f"Произведение (np.dot):\n{result_dot}\n")

Произведение (np.dot):
[[36.7187245  34.92828924 35.64928468 36.37393262 34.49875703]
 [30.32166635 28.90483454 29.59229999 29.74794314 28.51044839]
 [31.79940734 30.10554386 30.8098793  31.43329315 29.76636904]
 [35.38539955 33.92391113 34.34791164 35.26708785 33.26228711]
 [34.6221584  33.11573344 33.63151116 34.43319274 32.78632386]]



# 3. Создать вектор-строку 1x10 из случайных целых чисел. Вычислить норму ‖x‖1 самостоятельно написанной функцией и проверить результат с помощью linalg.norm().

In [8]:
vector = np.random.randint(1, 10, 10)
def norm_l1(x):
    return np.sum(np.abs(x))

norm_manual = norm_l1(vector)
norm_check = np.linalg.norm(vector, 1)

print(f"Норма L1 (вручную): {norm_manual}")
print(f"Норма L1 (linalg.norm): {norm_check}\n")

Норма L1 (вручную): 51
Норма L1 (linalg.norm): 51.0



# 4. Создать матрицу из случайных целых чисел. Найти спектральную норму матрицы с помощью самостоятельно написанного алгоритма (можно использовать функцию для нахождения собственных значений), проверить результат с помощью linalg.norm().

In [9]:
matrix_random = np.random.randint(-10, 10, (5, 5))

eigenvalues, _ = np.linalg.eig(matrix_random)
spectral_norm_manual = max(np.abs(eigenvalues))

spectral_norm_check = np.linalg.norm(matrix_random, 2)

print(f"Спектральная норма (вручную): {spectral_norm_manual}")
print(f"Спектральная норма (linalg.norm): {spectral_norm_check}\n")

Спектральная норма (вручную): 10.322910811044762
Спектральная норма (linalg.norm): 19.15175045300466



# 5. Для вектора, созданного в третьем пункте, найти отражение Хаусхолдера, которое обнуляет его координаты с 4 по 10.

In [10]:
def householder_reflection(v):
    v_ = v[3:]  # часть вектора с 4 по 10 элемент
    e = np.zeros_like(v_)
    e[0] = np.linalg.norm(v_)
    u = v_ - e
    u = u / np.linalg.norm(u)
    H = np.eye(len(v_)) - 2 * np.outer(u, u)
    v[3:] = H @ v_
    return v

vector_householder = householder_reflection(vector.copy())
print(f"Отражение Хаусхолдера: {vector_householder}\n")

Отражение Хаусхолдера: [ 7  2  3 16  0  0  0  0  0  0]



# 6. Для матрицы, созданной в 4 пункте, найти LU разложение самостоятельно написанной функцией и проверить результат с помощью перемножения матриц.

In [11]:
def lu_decomposition(matrix):
    n = len(matrix)
    L = np.eye(n)
    U = matrix.copy()
    
    for i in range(n):
        for j in range(i+1, n):
            factor = U[j, i] / U[i, i]
            L[j, i] = factor
            U[j, i:] = U[j, i:] - factor * U[i, i:]
    
    return L, U

L_manual, U_manual = lu_decomposition(matrix_random)

P, L_check, U_check = lu(matrix_random)

print(f"L (вручную):\n{L_manual}\n")
print(f"U (вручную):\n{U_manual}\n")
print(f"L (SciPy):\n{L_check}\n")
print(f"U (SciPy):\n{U_check}\n")

L (вручную):
[[ 1.         0.         0.         0.         0.       ]
 [ 1.25       1.         0.         0.         0.       ]
 [ 0.        -7.         1.         0.         0.       ]
 [-0.25       7.        -1.         1.         0.       ]
 [-2.5       16.        -2.7755102  0.9        1.       ]]

U (вручную):
[[  4   4   6   3  -1]
 [  0   1  -7   0   6]
 [  0   0 -49  -3  32]
 [  0   0   0 -10  -2]
 [  0   0   0   0  -9]]

L (SciPy):
[[ 1.          0.          0.          0.          0.        ]
 [-0.5         1.          0.          0.          0.        ]
 [-0.4         0.71111111  1.          0.          0.        ]
 [ 0.1         0.6        -0.71875     1.          0.        ]
 [-0.         -0.77777778  0.546875    0.75399645  1.        ]]

U (SciPy):
[[-10.           6.           9.          -9.          -2.        ]
 [  0.           9.           4.5         -1.5          4.        ]
 [  0.           0.           6.4          0.46666667  -4.64444444]
 [  0.           0.   

# 7. Для матрицы, созданной в 4 пункте, найти QR разложение всеми рассмотренными методами, проверить результат с помощью перемножения матриц и с помощью функции np.linalg.qr

In [12]:
def qr_gram_schmidt(A):
    n, m = A.shape
    Q = np.zeros((n, m))
    R = np.zeros((m, m))
    
    for j in range(m):
        v = A[:, j]
        for i in range(j):
            R[i, j] = np.dot(Q[:, i], A[:, j])
            v = v - R[i, j] * Q[:, i]
        R[j, j] = np.linalg.norm(v)
        Q[:, j] = v / R[j, j]
    
    return Q, R

Q_gs, R_gs = qr_gram_schmidt(matrix_random)

Q_check, R_check = qr(matrix_random)

print(f"Q (Грам-Шмидт):\n{Q_gs}\n")
print(f"R (Грам-Шмидт):\n{R_gs}\n")
print(f"Q (SciPy):\n{Q_check}\n")
print(f"R (SciPy):\n{R_check}\n")

Q (Грам-Шмидт):
[[ 0.33567254  0.34980696  0.76206654 -0.13854652  0.40622467]
 [ 0.41959068  0.51391393 -0.02318731 -0.00609672 -0.74783776]
 [ 0.         -0.5365866   0.32052769 -0.68566776 -0.37309053]
 [-0.08391814  0.44913486 -0.4490456  -0.7144641   0.28130893]
 [-0.83918136  0.35196626  0.33813752  0.01297944 -0.2395599 ]]

R (Грам-Шмидт):
[[11.91637529 -1.67836272 -5.45467883 10.48976698  2.68538035]
 [ 0.         13.04542443  4.81740328 -2.5598528  10.92390999]
 [ 0.          0.          8.06468254  1.80418176 -8.80096545]
 [ 0.          0.          0.          7.22197138  0.50860472]
 [ 0.          0.          0.          0.          2.59639197]]

Q (SciPy):
[[-0.33567254 -0.34980696 -0.76206654 -0.13854652  0.40622467]
 [-0.41959068 -0.51391393  0.02318731 -0.00609672 -0.74783776]
 [-0.          0.5365866  -0.32052769 -0.68566776 -0.37309053]
 [ 0.08391814 -0.44913486  0.4490456  -0.7144641   0.28130893]
 [ 0.83918136 -0.35196626 -0.33813752  0.01297944 -0.2395599 ]]

R (Sci

# часть 2


# 1. Создать произвольную верхнетреугольную матрицу А 5 порядка (не унитреугольную), вектор B произвольный. Решить систему AX = B методом обратной подстановки. Проверить решение методом np.solve

In [13]:
# Создаем верхнетреугольную матрицу A размером 5x5
A = np.array([
    [2, -1, 0, 0, 0],
    [0, 3, 1, 0, 0],
    [0, 0, 4, 2, 0],
    [0, 0, 0, 5, 1],
    [0, 0, 0, 0, 6]
])

# Создаем произвольный вектор B
B = np.array([1, 2, 3, 4, 5])

# Метод обратной подстановки
def back_substitution(A, B):
    n = len(B)
    X = np.zeros(n)
    for i in range(n-1, -1, -1):
        X[i] = (B[i] - np.dot(A[i, i+1:], X[i+1:])) / A[i, i]
    return X

# Решаем систему AX = B
X_custom = back_substitution(A, B)

# Проверяем решение с помощью np.solve
X_np = np.linalg.solve(A, B)

# Выводим результаты
print("Решение методом обратной подстановки:", X_custom)
print("Решение с помощью np.solve:", X_np)
print("Совпадают ли решения?:", np.allclose(X_custom, X_np))

Решение методом обратной подстановки: [0.76111111 0.52222222 0.43333333 0.63333333 0.83333333]
Решение с помощью np.solve: [0.76111111 0.52222222 0.43333333 0.63333333 0.83333333]
Совпадают ли решения?: True


# 2. Решить систему, используя LU разложение

In [14]:
# Определяем матрицу A и вектор B
A = np.array([
    [4.4, -2.5, 19.2, -10.8],
    [5.5, -9.3, -14.2, 13.2],
    [7.1, -11.5, 5.3, -6.7],
    [14.2, 23.4, -8.8, 5.3]
])

B = np.array([4.3, 6.8, -1.8, 7.2])

# Выполняем LU-разложение
P, L, U = lu(A)

# Решаем систему Ly = B
y = np.linalg.solve(L, B)

# Решаем систему Ux = y
X = np.linalg.solve(U, y)

print("Решение системы уравнений:", X)

Решение системы уравнений: [ 0.53592897 -0.04402285  0.06759248 -0.31797036]


# 3. Решить систему из пункта 2 с помощью QR разложения матрицы А. QR разложение найти методом Хаусхолдера. Проверить полученное решение непосредственной подстановкой в исходную систему, а также методом np.solve

In [15]:
# Определяем матрицу A и вектор B
A = np.array([
    [4.4, -2.5, 19.2, -10.8],
    [5.5, -9.3, -14.2, 13.2],
    [7.1, -11.5, 5.3, -6.7],
    [14.2, 23.4, -8.8, 5.3]
])

B = np.array([4.3, 6.8, -1.8, 7.2])

# Выполняем QR-разложение
Q, R = qr(A)

# Решаем систему Rx = Q^T * B
QT_B = np.dot(Q.T, B)
X = np.linalg.solve(R, QT_B)

# Проверяем решение, подставляя его в исходную систему
check = np.allclose(np.dot(A, X), B)

# Также решаем систему с помощью np.solve
X_np = np.linalg.solve(A, B)

# Выводим результаты
print("Решение системы уравнений (QR):", X)
print("Проверка (подстановка):", check)
print("Решение с помощью np.solve:", X_np)
print("Совпадают ли решения?:", np.allclose(X, X_np))

Решение системы уравнений (QR): [0.44483668 0.06731407 0.86853494 1.31156176]
Проверка (подстановка): True
Решение с помощью np.solve: [0.44483668 0.06731407 0.86853494 1.31156176]
Совпадают ли решения?: True


# 4. Решить систему методом простых итераций с точностью до 10^−3 . 

In [16]:
from prettytable import PrettyTable

In [22]:
x1, x2, x3 = 0, 0, 0
tolerance = 1e-3
max_iterations = 100
iterations = []

# Проверяем достаточное условие сходимости (норма по строкам)
matrix_norm = max([abs(3.3 / 2.7) + abs(1.3 / 2.7), abs(3.5 / 1.7) + abs(2.8 / 1.7), abs(4.1 / 1.7) + abs(5.8 / 1.7)])
if matrix_norm >= 1:
    print("Матрица не удовлетворяет условию сходимости. Требуется преобразование системы.")
else:
    print(f"Условие сходимости выполнено, норма матрицы: {matrix_norm:.4f}")

# Метод простых итераций
for i in range(max_iterations):
    x1_new = (2.1 - 3.3 * x2 - 1.3 * x3) / 2.7
    x2_new = (3.5 * x1 + 2.8 * x3 - 1.7) / 1.7
    x3_new = (4.1 * x1 + 5.8 * x2) / 1.7

    # Записываем итерацию
    iterations.append((i + 1, x1_new, x2_new, x3_new))

    # Проверяем сходимость
    if np.allclose([x1_new, x2_new, x3_new], [x1, x2, x3], atol=tolerance):
        break
    x1, x2, x3 = x1_new, x2_new, x3_new

table = PrettyTable()
table.field_names = ["Итерация", "x1", "x2", "x3"]
for iteration in iterations:
    table.add_row(iteration)

print(table)

Матрица не удовлетворяет условию сходимости. Требуется преобразование системы.
+----------+-------------------------+-------------------------+-------------------------+
| Итерация |            x1           |            x2           |            x3           |
+----------+-------------------------+-------------------------+-------------------------+
|    1     |    0.7777777777777778   |           -1.0          |           0.0           |
|    2     |           2.0           |    0.6013071895424837   |   -1.5359477124183007   |
|    3     |    0.7823771483902202   |    0.587850826605152    |    6.875048058439062    |
|    4     |   -3.2509148902843634   |    11.934385048820673   |    3.8925182957116378   |
|    5     |   -15.682868313160498   |   -1.2818534635309926   |    32.876871901761184   |
|    6     |    -13.48511742319899   |    20.861883664040924   |    -42.19677068966929   |
|    7     |    -4.403116368431467   |    -98.2640405366297    |    38.65290812724794    |
|    8     

# 5. Найти псевдорешение системы:

In [18]:
# Определяем матрицу A и вектор b
A = np.array([
    [4.4, -2.5, 19.2, -10.8],
    [5.5, -9.3, -14.2, 13.2],
    [7.1, -11.5, 5.3, -6.7],
    [14.2, 23.4, -8.8, 5.3],
    [8.2, -3.2, 14.2, 14.8]
])

b = np.array([4.3, 6.8, -1.8, 7.2, -8.4])

# Находим псевдорешение
x = np.linalg.inv(A.T @ A) @ A.T @ b

print("Псевдорешение системы:")
print(x)

Псевдорешение системы:
[ 0.38466722  0.02588808 -0.34336072 -0.32744471]
